# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-07 19:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0004_auto_20180305_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
